version: '3.8'
services:
  jsreport:
    image: jsreport/jsreport:latest
    # Add this line to run the container as root
    user: '0:0'
    ports:
      - '5488:5488'
    volumes:
      - jsreport_storage:/app/data

volumes:
  jsreport_storage:
